"""Offline browser UI tests, no policy bypass and no claim of real browser networking."""
import json,pathlib
from playwright.sync_api import sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1]
ART=ROOT/'tests/screenshots';ART.mkdir(exist_ok=True)
checks=[]
def check(name,v):
 assert v,name
 checks.append({'name':name,'status':'passed'});print('PASS',name,flush=True)
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
 page=browser.new_page(viewport={'width':1440,'height':1100},device_scale_factor=1)
 errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.set_content((ROOT/'web/index.html').read_text(),wait_until='load')
 check('accept disabled without consent',page.locator('[data-action=accept]').is_disabled())
 page.screenshot(path=str(ART/'01-request.png'),full_page=True)
 page.check('#consent');page.click('[data-action=accept]')
 check('accept opens on-demand connection dialog',page.locator('[role=dialog]').get_by_text('打开 assist，就能开始').is_visible())
 check('no preinstalled-tool prerequisite','不需要安装向导' in page.locator('.modal').inner_text())
 page.screenshot(path=str(ART/'02-connect.png'),full_page=True)
 page.click('[data-action=dev-open]');page.click('[data-action=mock-connect]');page.click('[data-action=dev-close]')
 check('simulated channel enters live page','一起看清' in page.locator('h1').inner_text())
 check('no automatic operation on connection','等待支持方提出命令' in page.locator('#terminalOutput').inner_text())
 page.click('[data-action=dev-open]');page.fill('#commandInput',"Write-Output 'hello from agent'")
 page.screenshot(path=str(ART/'03-developer.png'),full_page=True)
 page.click('[data-action=send-command]')
 check('developer submission creates approval before execution','有一条命令，需要你批准' in page.locator('.approval').inner_text())
 check('command editor text appears unchanged',"Write-Output 'hello from agent'" in page.locator('.approval pre').inner_text())
 page.screenshot(path=str(ART/'04-approval.png'),full_page=True)
 page.click('[data-action=deny]')
 check('denial produces no output','已拒绝' in page.locator('#terminalOutput').inner_text() and '预览占位' not in page.locator('#terminalOutput').inner_text())
 page.click('[data-action=dev-open]');page.click('[data-action=preset-info]');page.click('[data-action=send-command]');page.click('[data-action=approve]');page.wait_for_timeout(1900)
 check('approval displays explicitly labelled simulated output','模拟输出' in page.locator('#terminalOutput').inner_text() and 'exit 0' in page.locator('#terminalOutput').inner_text())
 page.screenshot(path=str(ART/'05-live.png'),full_page=True)
 page.set_viewport_size({'width':390,'height':844});page.screenshot(path=str(ART/'06-mobile.png'),full_page=True)
 check('mobile viewport has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth <= innerWidth+1'))
 page.set_viewport_size({'width':1440,'height':1100})
 page.click('[data-action=dev-open]');page.click('[data-action=preset-wait]');page.click('[data-action=send-command]');page.click('[data-action=approve]');page.wait_for_timeout(750)
 check('running command exposes stop control',page.locator('[data-action=cancel-command]').count()>0)
 page.locator('[data-action=cancel-command]').first.click()
 check('cancel changes terminal state','已取消' in page.locator('#terminalOutput').inner_text())
 page.click('[data-action=end-dialog]');page.click('[data-action=end-confirm]')
 check('completion distinguishes receipt from diagnosis','不等同于问题已解决' in page.locator('.page').inner_text())
 page.screenshot(path=str(ART/'07-complete.png'),full_page=True)
 page.click('[data-action=dev-open]');page.click('[data-action=mock-cleanup]');page.click('[data-action=dev-close]')
 check('missing receipt is not success','执行器停止尚待确认' in page.locator('.page').inner_text())
 page.screenshot(path=str(ART/'08-cleanup-pending.png'),full_page=True)
 page.click('[data-action=dev-open]');page.click('[data-action=fixture-live]');page.click('[data-action=devtab-flow]')
 check('flow documentation is removable developer content','页面关联与职责' in page.locator('.drawer').inner_text())
 page.click('[data-action=dev-close]')
 # replay real integration states only to test render/escaping. This remains offline.
 actual=json.loads((ROOT/'tests/state-live.json').read_text())
 page.evaluate('s=>{previewStage=null;S=s;render()}',actual)
 check('real recorded stderr/exit renders faithfully','stderr: diagnostic' in page.locator('#terminalOutput').inner_text() and 'exit 7' in page.locator('#terminalOutput').inner_text())
 page.evaluate('S.operations[0].outputs.push({stream:"stdout",text:"<img src=x onerror=alert(1)>"});render()')
 check('terminal output escaped, not rendered as HTML',page.locator('#terminalOutput img').count()==0 and '<img src=x' in page.locator('#terminalOutput').inner_text())
 # developer removal does not remove customer workflow
 page=browser.new_page(viewport={'width':1440,'height':1100});page.on('pageerror',lambda e:errors.append(str(e)));page.set_content((ROOT/'web/index.html').read_text().replace('const ENABLE_DEVTOOLS=true;','const ENABLE_DEVTOOLS=false;'),wait_until='load')
 check('developer controls removable by single flag',page.locator('.dev-entry').count()==0 and page.locator('[data-action=accept]').count()==1)
 check('no uncaught JS errors',not errors)
 browser.close()
(ROOT/'tests/ui-results.json').write_text(json.dumps({'scope':'offline Chromium DOM + interactions only','checks':checks,'browser_network':'managed browser URLBlocklist blocks network navigation; not modified or bypassed','windows_native':'not tested'},ensure_ascii=False,indent=2))
